<?php 
 return array (
  'CLOUD_USERNAME' => '',
  'CLOUD_PASSWORD' => '',
  'COOKIE_EXPIRE' => '3600',
  'COOKIE_DOMAIN' => '',
  'COOKIE_PATH' => '',
  'SESSION_PREFIX' => '',
  'SESSION_OPTIONS' => 
  array (
    'domain' => '',
  ),
  'SHOW_ERROR_MSG' => '0',
  'ERROR_MESSAGE' => '',
  'ERROR_PAGE' => '',
  'URL_CASE_INSENSITIVE' => '0',
  'URL_MODEL' => 0,
  'URL_PATHINFO_DEPR' => '/',
  'URL_HTML_SUFFIX' => '',
  'TOKEN_ON' => '1',
  'TOKEN_NAME' => '__hash__',
  'TOKEN_TYPE' => 'md5',
  'PAGE_LISTROWS' => '20',
  'VAR_PAGE' => 'page',
  'PAGE_TEMPLATE' => '',
  'DEFAULT_MODULE' => '',
  'DEFAULT_TIMEZONE' => 'PRC',
  'DEFAULT_AJAX_RETURN' => 'JSON',
  'DEFAULT_FILTER' => '',
  'DEFAULT_LANG' => 'zh-cn',
  'DATA_CACHE_TYPE' => 'File',
  'DATA_CACHE_SUBDIR' => '0',
  'LOAD_EXT_FILE' => '',
  'default_group' => 'content',
  'token_on' => false,
  'url_convert' => false,
  'CLOUD_ON' => false,
);